var productsList = [
  {
    "product_id": "5305817628836",
    "name": "Men's Royal Albartross Golf Shoes | The Driver Black",
    "product_url": "https://golftini.myshopify.com/products/mens-royal-albartross-golf-shoes-the-driver-black",
    "price": "229.00",
    "inv_tracked": "0",
    "inventory": "0",
    "handle": "mens-royal-albartross-golf-shoes-the-driver-black",
    "category": "Golf_Shoes",
    "vendor": "Royal Albartross",
    "aspect": "1.5041128084606346",
    "active": "1",
    "image_url": "https://cdn.shopify.com/s/files/1/2599/5098/products/blackdriver2.jpg?v=1591747755"
  },
  {
    "product_id": "5305817628836",
    "name": "Men's Royal Albartross Golf Shoes | The Driver Black",
    "product_url": "https://golftini.myshopify.com/products/mens-royal-albartross-golf-shoes-the-driver-black",
    "price": "229.00",
    "inv_tracked": "0",
    "inventory": "0",
    "handle": "mens-royal-albartross-golf-shoes-the-driver-black",
    "category": "Golf_Shoes",
    "vendor": "Royal Albartross",
    "aspect": "1.5041128084606346",
    "active": "1",
    "image_url": "https://cdn.shopify.com/s/files/1/2599/5098/products/blackdriver2.jpg?v=1591747755"
  },
  {
    "product_id": "5305817628836",
    "name": "Men's Royal Albartross Golf Shoes | The Driver Black",
    "product_url": "https://golftini.myshopify.com/products/mens-royal-albartross-golf-shoes-the-driver-black",
    "price": "229.00",
    "inv_tracked": "0",
    "inventory": "0",
    "handle": "mens-royal-albartross-golf-shoes-the-driver-black",
    "category": "Golf_Shoes",
    "vendor": "Royal Albartross",
    "aspect": "1.5041128084606346",
    "active": "1",
    "image_url": "https://cdn.shopify.com/s/files/1/2599/5098/products/blackdriver2.jpg?v=1591747755"
  },
  {
    "product_id": "5305817628836",
    "name": "Men's Royal Albartross Golf Shoes | The Driver Black",
    "product_url": "https://golftini.myshopify.com/products/mens-royal-albartross-golf-shoes-the-driver-black",
    "price": "229.00",
    "inv_tracked": "0",
    "inventory": "0",
    "handle": "mens-royal-albartross-golf-shoes-the-driver-black",
    "category": "Golf_Shoes",
    "vendor": "Royal Albartross",
    "aspect": "1.5041128084606346",
    "active": "1",
    "image_url": "https://cdn.shopify.com/s/files/1/2599/5098/products/blackdriver2.jpg?v=1591747755"
  },
];
